version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: '(?i):shipit:|:\\+1:|LGTM'
      enabled: true
      reject_regex: ^Rejected
    required: 1
    reset_on_push:
      enabled: false
    users:
    - ace0625
    - festinalente91
    - ochanje210
